<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TP04j3cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TP04j3c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TP04j3c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demande' => ['privates', '.errored..service_locator.TP04j3c.App\\Entity\\DemandeDon', NULL, 'Cannot autowire service ".service_locator.TP04j3c": it needs an instance of "App\\Entity\\DemandeDon" but this type has been excluded in "config/services.yaml".'],
            'reponseRepo' => ['privates', 'App\\Repository\\ReponseDonRepository', 'getReponseDonRepositoryService', true],
        ], [
            'demande' => 'App\\Entity\\DemandeDon',
            'reponseRepo' => 'App\\Repository\\ReponseDonRepository',
        ]);
    }
}
