<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q3DzzdLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q3DzzdL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q3DzzdL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'analyseAI' => ['privates', '.errored..service_locator.Q3DzzdL.App\\Entity\\AnalyseAI', NULL, 'Cannot autowire service ".service_locator.Q3DzzdL": it needs an instance of "App\\Entity\\AnalyseAI" but this type has been excluded in "config/services.yaml".'],
        ], [
            'analyseAI' => 'App\\Entity\\AnalyseAI',
        ]);
    }
}
