<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V_U335nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V.U335n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V.U335n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\LieuMedicalRepository', 'getLieuMedicalRepositoryService', true],
            'reviewRepository' => ['privates', 'App\\Repository\\LieuMedicalReviewRepository', 'getLieuMedicalReviewRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\LieuMedicalRepository',
            'reviewRepository' => 'App\\Repository\\LieuMedicalReviewRepository',
        ]);
    }
}
