<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N_7ixsCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N.7ixsC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N.7ixsC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demande' => ['privates', '.errored..service_locator.N.7ixsC.App\\Entity\\DemandeDon', NULL, 'Cannot autowire service ".service_locator.N.7ixsC": it needs an instance of "App\\Entity\\DemandeDon" but this type has been excluded in "config/services.yaml".'],
        ], [
            'demande' => 'App\\Entity\\DemandeDon',
        ]);
    }
}
