<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dy5Wk7zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dy5Wk7z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dy5Wk7z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'donneur' => ['privates', '.errored..service_locator.dy5Wk7z.App\\Entity\\Donneur', NULL, 'Cannot autowire service ".service_locator.dy5Wk7z": it needs an instance of "App\\Entity\\Donneur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'donneur' => 'App\\Entity\\Donneur',
        ]);
    }
}
