<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XjMC5mjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xjMC5mj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xjMC5mj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ticketRepository' => ['privates', 'App\\Repository\\SupportTicketRepository', 'getSupportTicketRepositoryService', true],
        ], [
            'ticketRepository' => 'App\\Repository\\SupportTicketRepository',
        ]);
    }
}
