<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UoYCD8RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UoYCD8R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UoYCD8R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lieu' => ['privates', '.errored..service_locator.UoYCD8R.App\\Entity\\LieuMedical', NULL, 'Cannot autowire service ".service_locator.UoYCD8R": it needs an instance of "App\\Entity\\LieuMedical" but this type has been excluded in "config/services.yaml".'],
            'qrCodeService' => ['privates', 'App\\Service\\QrCodeService', 'getQrCodeServiceService', true],
        ], [
            'lieu' => 'App\\Entity\\LieuMedical',
            'qrCodeService' => 'App\\Service\\QrCodeService',
        ]);
    }
}
