<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fl4rKbrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fl4rKbr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fl4rKbr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hopitalRepository' => ['privates', 'App\\Repository\\HopitalRepository', 'getHopitalRepositoryService', true],
        ], [
            'hopitalRepository' => 'App\\Repository\\HopitalRepository',
        ]);
    }
}
