<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BWb6wbrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bWb6wbr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactRepo' => ['privates', 'App\\Repository\\ContactUrgenceRepository', 'getContactUrgenceRepositoryService', true],
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
        ], [
            'contactRepo' => 'App\\Repository\\ContactUrgenceRepository',
            'emailService' => 'App\\Service\\EmailService',
        ]);

        if (isset($container->privates['.service_locator.bWb6wbr'])) {
            return $container->privates['.service_locator.bWb6wbr'];
        }

        return $container->privates['.service_locator.bWb6wbr'] = $instance;
    }
}
