<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UHlxBWuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UHlxBWu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lieu' => ['privates', '.errored..service_locator.UHlxBWu.App\\Entity\\LieuMedical', NULL, 'Cannot autowire service ".service_locator.UHlxBWu": it needs an instance of "App\\Entity\\LieuMedical" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'lieu' => 'App\\Entity\\LieuMedical',
        ]);

        if (isset($container->privates['.service_locator.UHlxBWu'])) {
            return $container->privates['.service_locator.UHlxBWu'];
        }

        return $container->privates['.service_locator.UHlxBWu'] = $instance;
    }
}
