<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QVgfJWRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qVgfJWR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qVgfJWR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hopital' => ['privates', '.errored..service_locator.qVgfJWR.App\\Entity\\Hopital', NULL, 'Cannot autowire service ".service_locator.qVgfJWR": it needs an instance of "App\\Entity\\Hopital" but this type has been excluded in "config/services.yaml".'],
        ], [
            'hopital' => 'App\\Entity\\Hopital',
        ]);
    }
}
