<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_34wTWnlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.34wTWnl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactRepo' => ['privates', 'App\\Repository\\ContactUrgenceRepository', 'getContactUrgenceRepositoryService', true],
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'smsService' => ['privates', 'App\\Service\\SmsService', 'getSmsServiceService', true],
            'voiceAssistant' => ['privates', 'App\\Service\\VoiceAssistantService', 'getVoiceAssistantServiceService', true],
        ], [
            'contactRepo' => 'App\\Repository\\ContactUrgenceRepository',
            'emailService' => 'App\\Service\\EmailService',
            'smsService' => 'App\\Service\\SmsService',
            'voiceAssistant' => 'App\\Service\\VoiceAssistantService',
        ]);

        if (isset($container->privates['.service_locator.34wTWnl'])) {
            return $container->privates['.service_locator.34wTWnl'];
        }

        return $container->privates['.service_locator.34wTWnl'] = $instance;
    }
}
