<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6E8m7BPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6E8m7BP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'urgence' => ['privates', '.errored..service_locator.6E8m7BP.App\\Entity\\Urgence', NULL, 'Cannot autowire service ".service_locator.6E8m7BP": it needs an instance of "App\\Entity\\Urgence" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'urgence' => 'App\\Entity\\Urgence',
        ]);

        if (isset($container->privates['.service_locator.6E8m7BP'])) {
            return $container->privates['.service_locator.6E8m7BP'];
        }

        return $container->privates['.service_locator.6E8m7BP'] = $instance;
    }
}
