<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PmS5qjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pm_s5qj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactRepo' => ['privates', 'App\\Repository\\ContactUrgenceRepository', 'getContactUrgenceRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'smsService' => ['privates', 'App\\Service\\SmsService', 'getSmsServiceService', true],
        ], [
            'contactRepo' => 'App\\Repository\\ContactUrgenceRepository',
            'em' => '?',
            'emailService' => 'App\\Service\\EmailService',
            'smsService' => 'App\\Service\\SmsService',
        ]);

        if (isset($container->privates['.service_locator.pm_s5qj'])) {
            return $container->privates['.service_locator.pm_s5qj'];
        }

        return $container->privates['.service_locator.pm_s5qj'] = $instance;
    }
}
