<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ku6K56IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ku6K56I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ku6K56I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tutorial' => ['privates', '.errored..service_locator.Ku6K56I.App\\Entity\\VideoTutorial', NULL, 'Cannot autowire service ".service_locator.Ku6K56I": it needs an instance of "App\\Entity\\VideoTutorial" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tutorial' => 'App\\Entity\\VideoTutorial',
        ]);
    }
}
