<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jmwc7__Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jmwc7..' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jmwc7..'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'analyseAIRepository' => ['privates', 'App\\Repository\\AnalyseAIRepository', 'getAnalyseAIRepositoryService', true],
        ], [
            'analyseAIRepository' => 'App\\Repository\\AnalyseAIRepository',
        ]);
    }
}
