<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GXgpB_QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gXgpB.q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gXgpB.q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ticket' => ['privates', '.errored..service_locator.gXgpB.q.App\\Entity\\SupportTicket', NULL, 'Cannot autowire service ".service_locator.gXgpB.q": it needs an instance of "App\\Entity\\SupportTicket" but this type has been excluded in "config/services.yaml".'],
        ], [
            'ticket' => 'App\\Entity\\SupportTicket',
        ]);
    }
}
