<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S5EyumeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S5Eyume' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demande' => ['privates', '.errored..service_locator.S5Eyume.App\\Entity\\DemandeDon', NULL, 'Cannot autowire service ".service_locator.S5Eyume": it needs an instance of "App\\Entity\\DemandeDon" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'demande' => 'App\\Entity\\DemandeDon',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.S5Eyume'])) {
            return $container->privates['.service_locator.S5Eyume'];
        }

        return $container->privates['.service_locator.S5Eyume'] = $instance;
    }
}
