<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertificateServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CertificateService' shared autowired service.
     *
     * @return \App\Service\CertificateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CertificateService.php';

        $a = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->privates['App\\Service\\CertificateService'])) {
            return $container->privates['App\\Service\\CertificateService'];
        }

        $instance = new \App\Service\CertificateService($a, ($container->privates['App\\Service\\QrCodeService'] ?? $container->load('getQrCodeServiceService')));

        if (isset($container->privates['App\\Service\\CertificateService'])) {
            return $container->privates['App\\Service\\CertificateService'];
        }

        return $container->privates['App\\Service\\CertificateService'] = $instance;
    }
}
