<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDonneurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8NRvP_e.App\Entity\Donneur' shared service.
     *
     * @return \App\Entity\Donneur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8NRvP_e": it needs an instance of "App\\Entity\\Donneur" but this type has been excluded in "config/services.yaml".');
    }
}
