<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailUrgenceCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\EmailUrgenceCommand' shared autowired service.
     *
     * @return \App\Command\EmailUrgenceCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'EmailUrgenceCommand.php';

        $container->privates['App\\Command\\EmailUrgenceCommand'] = $instance = new \App\Command\EmailUrgenceCommand(($container->privates['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService')));

        $instance->setName('email:urgence');
        $instance->setDescription('Test urgency email notification');

        return $instance;
    }
}
