<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLieuMedicalReviewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.32Lj85L.App\Entity\LieuMedicalReview' shared service.
     *
     * @return \App\Entity\LieuMedicalReview
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.32Lj85L": it needs an instance of "App\\Entity\\LieuMedicalReview" but this type has been excluded in "config/services.yaml".');
    }
}
