<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SmsService' shared autowired service.
     *
     * @return \App\Service\SmsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SmsService.php';

        return $container->privates['App\\Service\\SmsService'] = new \App\Service\SmsService($container->getEnv('VONAGE_API_KEY'), $container->getEnv('VONAGE_API_SECRET'), $container->getEnv('VONAGE_BRAND'));
    }
}
