<?php

namespace ContainerOkRWvUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUrgenceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6E8m7BP.App\Entity\Urgence' shared service.
     *
     * @return \App\Entity\Urgence
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6E8m7BP": it needs an instance of "App\\Entity\\Urgence" but this type has been excluded in "config/services.yaml".');
    }
}
