stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true  # Gestion automatique created_at, updated_at
            sluggable: true      # Génération automatique de slugs
            blameable: true      # Suivi de qui a modifié