vich_uploader:
    db_driver: orm
    
    mappings:
        medical_documents:
            uri_prefix: /uploads/medical
            upload_destination: '%kernel.project_dir%/public/uploads/medical'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true