<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TWnNEX5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tWnNEX5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certificateService' => ['privates', 'App\\Service\\CertificateService', 'getCertificateServiceService', true],
            'don' => ['privates', '.errored..service_locator.tWnNEX5.App\\Entity\\Don', NULL, 'Cannot autowire service ".service_locator.tWnNEX5": it needs an instance of "App\\Entity\\Don" but this type has been excluded in "config/services.yaml".'],
        ], [
            'certificateService' => 'App\\Service\\CertificateService',
            'don' => 'App\\Entity\\Don',
        ]);

        if (isset($container->privates['.service_locator.tWnNEX5'])) {
            return $container->privates['.service_locator.tWnNEX5'];
        }

        return $container->privates['.service_locator.tWnNEX5'] = $instance;
    }
}
