<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xszx13XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xszx13X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xszx13X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hopitalRepository' => ['privates', 'App\\Repository\\HopitalRepository', 'getHopitalRepositoryService', true],
            'rendezVousRepository' => ['privates', 'App\\Repository\\RendezVousRepository', 'getRendezVousRepositoryService', true],
        ], [
            'hopitalRepository' => 'App\\Repository\\HopitalRepository',
            'rendezVousRepository' => 'App\\Repository\\RendezVousRepository',
        ]);
    }
}
