<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AmSUs8QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.amSUs8Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.amSUs8Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lieu' => ['privates', '.errored..service_locator.amSUs8Q.App\\Entity\\LieuMedical', NULL, 'Cannot autowire service ".service_locator.amSUs8Q": it needs an instance of "App\\Entity\\LieuMedical" but this type has been excluded in "config/services.yaml".'],
            'reviewRepository' => ['privates', 'App\\Repository\\LieuMedicalReviewRepository', 'getLieuMedicalReviewRepositoryService', true],
        ], [
            'lieu' => 'App\\Entity\\LieuMedical',
            'reviewRepository' => 'App\\Repository\\LieuMedicalReviewRepository',
        ]);
    }
}
