<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TRHkncgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TRHkncg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TRHkncg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'don' => ['privates', '.errored..service_locator.TRHkncg.App\\Entity\\Don', NULL, 'Cannot autowire service ".service_locator.TRHkncg": it needs an instance of "App\\Entity\\Don" but this type has been excluded in "config/services.yaml".'],
        ], [
            'don' => 'App\\Entity\\Don',
        ]);
    }
}
