<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ESA3vseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ESA3vse' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ESA3vse'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'faq' => ['privates', '.errored..service_locator.ESA3vse.App\\Entity\\FAQ', NULL, 'Cannot autowire service ".service_locator.ESA3vse": it needs an instance of "App\\Entity\\FAQ" but this type has been excluded in "config/services.yaml".'],
        ], [
            'faq' => 'App\\Entity\\FAQ',
        ]);
    }
}
