<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_32Lj85LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.32Lj85L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.32Lj85L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'review' => ['privates', '.errored..service_locator.32Lj85L.App\\Entity\\LieuMedicalReview', NULL, 'Cannot autowire service ".service_locator.32Lj85L": it needs an instance of "App\\Entity\\LieuMedicalReview" but this type has been excluded in "config/services.yaml".'],
        ], [
            'review' => 'App\\Entity\\LieuMedicalReview',
        ]);
    }
}
