<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yus6pqIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yus6pqI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yus6pqI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactRepo' => ['privates', 'App\\Repository\\ContactUrgenceRepository', 'getContactUrgenceRepositoryService', true],
            'lieuRepo' => ['privates', 'App\\Repository\\LieuMedicalRepository', 'getLieuMedicalRepositoryService', true],
            'urgenceRepo' => ['privates', 'App\\Repository\\UrgenceRepository', 'getUrgenceRepositoryService', true],
        ], [
            'contactRepo' => 'App\\Repository\\ContactUrgenceRepository',
            'lieuRepo' => 'App\\Repository\\LieuMedicalRepository',
            'urgenceRepo' => 'App\\Repository\\UrgenceRepository',
        ]);
    }
}
