<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MJLhna5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MJLhna5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contact' => ['privates', '.errored..service_locator.MJLhna5.App\\Entity\\ContactUrgence', NULL, 'Cannot autowire service ".service_locator.MJLhna5": it needs an instance of "App\\Entity\\ContactUrgence" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'contact' => 'App\\Entity\\ContactUrgence',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.MJLhna5'])) {
            return $container->privates['.service_locator.MJLhna5'];
        }

        return $container->privates['.service_locator.MJLhna5'] = $instance;
    }
}
