<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8NRvPEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8NRvP_e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8NRvP_e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'donneur' => ['privates', '.errored..service_locator.8NRvP_e.App\\Entity\\Donneur', NULL, 'Cannot autowire service ".service_locator.8NRvP_e": it needs an instance of "App\\Entity\\Donneur" but this type has been excluded in "config/services.yaml".'],
            'qrCodeService' => ['privates', 'App\\Service\\QrCodeService', 'getQrCodeServiceService', true],
        ], [
            'donneur' => 'App\\Entity\\Donneur',
            'qrCodeService' => 'App\\Service\\QrCodeService',
        ]);
    }
}
