<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LvQodsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._lvQods' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'analyseAI' => ['privates', '.errored..service_locator._lvQods.App\\Entity\\AnalyseAI', NULL, 'Cannot autowire service ".service_locator._lvQods": it needs an instance of "App\\Entity\\AnalyseAI" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'analyseAI' => 'App\\Entity\\AnalyseAI',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator._lvQods'])) {
            return $container->privates['.service_locator._lvQods'];
        }

        return $container->privates['.service_locator._lvQods'] = $instance;
    }
}
