<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DQlWcYaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DQlWcYa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DQlWcYa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\FAQRepository', 'getFAQRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\FAQRepository',
        ]);
    }
}
