<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalyseAI2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._lvQods.App\Entity\AnalyseAI' shared service.
     *
     * @return \App\Entity\AnalyseAI
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._lvQods": it needs an instance of "App\\Entity\\AnalyseAI" but this type has been excluded in "config/services.yaml".');
    }
}
