<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactUrgenceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MJLhna5.App\Entity\ContactUrgence' shared service.
     *
     * @return \App\Entity\ContactUrgence
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MJLhna5": it needs an instance of "App\\Entity\\ContactUrgence" but this type has been excluded in "config/services.yaml".');
    }
}
