<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailTestCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\EmailTestCommand' shared autowired service.
     *
     * @return \App\Command\EmailTestCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'EmailTestCommand.php';

        $container->privates['App\\Command\\EmailTestCommand'] = $instance = new \App\Command\EmailTestCommand(($container->privates['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService')));

        $instance->setName('email:test');
        $instance->setDescription('Send a test email via Mailtrap');

        return $instance;
    }
}
