<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailUrgenceCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\EmailUrgenceCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\EmailUrgenceCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('email:urgence', [], 'Test urgency email notification', false, #[\Closure(name: 'App\\Command\\EmailUrgenceCommand')] fn (): \App\Command\EmailUrgenceCommand => ($container->privates['App\\Command\\EmailUrgenceCommand'] ?? $container->load('getEmailUrgenceCommandService')));
    }
}
