<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLieuMedical4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.amSUs8Q.App\Entity\LieuMedical' shared service.
     *
     * @return \App\Entity\LieuMedical
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.amSUs8Q": it needs an instance of "App\\Entity\\LieuMedical" but this type has been excluded in "config/services.yaml".');
    }
}
