<?php

namespace ContainerZ3uUI1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupportTicketService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HAmrVXL.App\Entity\SupportTicket' shared service.
     *
     * @return \App\Entity\SupportTicket
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.HAmrVXL": it needs an instance of "App\\Entity\\SupportTicket" but this type has been excluded in "config/services.yaml".');
    }
}
