<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLOhuQeb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLOhuQeb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLOhuQeb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLOhuQeb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLOhuQeb\App_KernelDevDebugContainer([
    'container.build_hash' => 'LOhuQeb',
    'container.build_id' => 'db7fdaa1',
    'container.build_time' => 1778560194,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLOhuQeb');
