<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ3uUI1y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ3uUI1y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ3uUI1y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ3uUI1y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ3uUI1y\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z3uUI1y',
    'container.build_id' => 'dc1fc82e',
    'container.build_time' => 1772008835,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ3uUI1y');
