<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMhWv1dU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMhWv1dU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMhWv1dU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMhWv1dU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMhWv1dU\App_KernelDevDebugContainer([
    'container.build_hash' => 'MhWv1dU',
    'container.build_id' => 'b48c5817',
    'container.build_time' => 1772499807,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMhWv1dU');
