<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.56a55bda.js',
                '/build/742.c3ae2860.js',
                '/build/app.b5e10883.js',
            ],
            'css' => [
                '/build/app.6aa5b1ba.css',
            ],
        ],
    ],
],

]];
